[package]
name = "rust_music"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
rodio = "0.20.1"
druid = "0.8.3"
cpal = "0.15"
